# Generated by Django 5.0 on 2023-12-14 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_vendor_average_response_time_vendor_fulfillment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
