# Generated by Django 5.0 on 2023-12-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_code',
        ),
    ]
