# Generated by Django 5.0 on 2023-12-14 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
