# Generated by Django 5.0 on 2023-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.UUIDField(),
        ),
    ]
