# Generated by Django 5.0 on 2023-12-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_vendor_average_response_time_vendor_fulfillment_rate_and_more'),
    ]

    operations = [
    ]
