# Generated by Django 5.0 on 2023-12-16 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20231216_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
