# Generated by Django 5.0 on 2023-12-16 14:32

import hello.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=hello.models.generate_uuid, max_length=50, unique=True),
        ),
    ]
